### PR TITLE
Redmine 3.4.x testing

### LINKED ISSUE #15: Redmine 3.4 compatibility?
Plugin seems broken in Redmine 3.4. 

When I call /issues:
```
[2017-07-18 17:27:52.516 +0300] (31069)  INFO index.html.erb:106:in `block in _plugins_redmine_hide_estimated_hours_app_views_issues_index_html_erb__3632354224006244890_32259320'   Rendered issues/_sidebar.html.erb (12.0ms)
[2017-07-18 17:27:52.519 +0300] (31069)  INFO issues_controller.rb:51:in `block (2 levels) in index'   Rendered plugins/redmine_hide_estimated_hours/app/views/issues/index.html.erb within layouts/base (121.2ms)
[2017-07-18 17:27:52.520 +0300] (31069)  INFO  Completed 500 Internal Server Error in 311ms (ActiveRecord: 94.7ms)
[2017-07-18 17:27:52.522 +0300] (31069) FATAL  
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    118:                                 :title => l(:label_changes_details)) %>
    119: <% end %>
    120: 
    121: <%= context_menu issues_context_menu_path %>
  app/helpers/application_helper.rb:1300:in `context_menu'
  plugins/redmine_hide_estimated_hours/app/views/issues/index.html.erb:121:in `_plugins_redmine_hide_estimated_hours_app_views_issues_index_html_erb__3632354224006244890_32259320'
  app/controllers/issues_controller.rb:51:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

### PR DESCRIPTION
**Pull request by LVMBDV**
Updated views and mixin classes to 3.4 version of their counterparts, applied the changes that was done in the 3.2 branch. Tested with Redmine 3.4.2. This fixes #15.

### CODE REVIEW

**Comment by BenoitDuffez** [comment]
@return1: care to accept the PR? This made the plugin work on Redmine 3.4.
@LVMBDV: Thanks a lot :+1:

**Comment by LVMBDV** [comment]
I forked the project (only the >=3.4 part) over to [LVMBDV/redmine_hide_estimated_hours](https://github.com/LVMBDV/redmine_hide_estimated_hours) after months of inactivity from the original author. Contribute over there if something is missing or you've ported it to a new version.

P.S. I'm willing to merge into this project if the original author becomes active again.

**Comment by BenoitDuffez** [comment]
I wouldn't mind using your fork if it's the one that is maintained. I have actually cloned your repo on my redmine instance, however in the init file the URL is still here. So maybe change the URL in your fork until (if ever?) this repo becomes again the maintained one.

**Comment by return1** [comment]
it will, just a bit busy atm

**Comment by BenoitDuffez** [comment]
Great news! No need to hurry though (at least for me) because the fork is suitable until my next Redmine upgrade.

Thanks a lot for the quick feedback.
Cheers

**Comment by LVMBDV** [comment]
Fixed the init file. Will delete the repo when this PR gets merged.

**Comment by LVMBDV** [comment]
Kinda late but happy 1st birthday #16 :)

**Comment by return1** [comment]
Please stop doing this. Such comments are exactly those, which drive ppl out of open source.

I am very happy to send you my hourly rates, so you can hire me, if you need this done asap. Or you will have to wait until i have time to review and test your PR. Until that, your PR is documented here and in your fork, so it is not lost and people are finding it, so your work is appreciated ;)

**Comment by LVMBDV** [comment]
I'm just joking around. I don't have much emotional investment in this. I did it during an unpaid internship. Also it seems that not getting paid is more likely to drive people out of open source, not witty remarks :^)

**Comment by return1** [comment]
merged and fixed, thank you.

**Pull request closed without merging**
